apiVersion: v1
kind: Pod
metadata:
  name: reactive-tracks
spec:
  restartPolicy: Never
  containers:
  - name: proteus
    image: "netifi/proteus:1.5.0"
    ports:
    - name: communication
      protocol: TCP
      containerPort: 8001
    - name: admin
      protocol: TCP
      containerPort: 7001
    - name: console
      protocol: TCP
      containerPort: 9000
    env:
    - name: BROKER_SERVER_OPTS
      value: "-Dnetifi.authentication.0.accessKey=9007199254740991 -Dnetifi.broker.console.enabled=true -Dnetifi.authentication.0.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY= -Dnetifi.broker.admin.accessKey=9007199254740991 -Dnetifi.broker.admin.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY="



